# Generated by Django 3.2 on 2024-08-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sent',
        ),
    ]
