# Generated by Django 3.2 on 2024-08-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('station_id', models.CharField(max_length=20)),
                ('sent_a_report_to_WMATA', models.CharField(max_length=20)),
                ('WMATA', models.CharField(max_length=20)),
                ('mezzanine_id', models.CharField(max_length=20)),
                ('mezzanine_name', models.CharField(max_length=20)),
                ('incident_description', models.CharField(max_length=100)),
                ('maximo', models.CharField(max_length=20)),
                ('requester_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('incident_date', models.DateTimeField()),
                ('faregate_no', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('related_parts', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=20)),
                ('old_serial_no', models.CharField(max_length=20)),
                ('new_serial_no', models.CharField(max_length=20)),
                ('received_by', models.CharField(max_length=20)),
                ('Technician', models.CharField(max_length=20)),
                ('related_system', models.CharField(max_length=20)),
                ('action_logs', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=500)),
            ],
        ),
    ]
