# Generated by Django 3.2 on 2024-08-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='incident_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='modified_date',
            field=models.DateField(),
        ),
    ]
