# Generated by Django 3.2 on 2024-08-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0004_auto_20240807_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='incident_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='modified_date',
            field=models.DateField(null=True),
        ),
    ]
