# Generated by Django 3.2 on 2024-08-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0005_auto_20240807_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='ticket_id',
            new_name='t_id',
        ),
    ]
