# Generated by Django 3.2 on 2024-08-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0006_rename_ticket_id_tickets_t_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='t_id',
            new_name='ticket_id',
        ),
    ]
