# Generated by Django 3.2 on 2024-08-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0007_rename_t_id_tickets_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='t_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
