# Generated by Django 3.2 on 2024-08-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0008_tickets_t_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='id',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='t_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
