# Generated by Django 3.2 on 2024-08-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0009_auto_20240807_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='WMATA',
            new_name='ticket',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_id',
        ),
    ]
