# Generated by Django 3.2 on 2024-08-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0013_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='t_id',
        ),
        migrations.AddField(
            model_name='tickets',
            name='id',
            field=models.BigAutoField(auto_created=True, default=21, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
